version: 1.0.{build}
os: Visual Studio 2015
configuration: Release

# enable AssemblyInfo.cs patching with build version number 
assembly_info: 
 patch: true 
 file: AssemblyInfo.* 
 assembly_version: "{version}" 
 assembly_file_version: "{version}" 
 assembly_informational_version: "{version}" 

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  
build:
 verbosity: minimal
